### ISSUE TITLE
Ship own filepicker code

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud-libraries/nextcloud-dialogs#1]
Right now we just delegate, but ideally this package should be independent

**Comment by StCyr** [comment]
Is it me or is there a lot of typos in this part of the code?:

https://github.com/nextcloud/nextcloud-dialogs/blob/c805338bd184bdfed37dbc4d898c723935ec60a3/lib/filepicker.ts#L14

Should be `multiselect`

https://github.com/nextcloud/nextcloud-dialogs/blob/c805338bd184bdfed37dbc4d898c723935ec60a3/lib/filepicker.ts#L15

Should be `mimetypeFilter`

**Comment by ChristophWurst** [comment]
what typo?

**Comment by StCyr** [comment]
hmm I must have been tired when I wrote this comment. 

I think it's because I saw that:

	filepicker: function(title, callback, multiselect, mimetypeFilter, modal, type, path, options) {
https://github.com/nextcloud/server/blob/26a20ed13f782418b37c16681a7ad7a0c8e943b6/core/src/OC/dialogs.js#L225

I was investigating why, in the Mail app, selecting multiple attachments from Files was not working...

**Comment by ChristophWurst** [comment]
ah. I think we possible just improved the naming here. the library isn't mean to be an identical drop-in replacement

**Comment by susnux** [comment]
Planning to do this for the file picker improvments.
