### ISSUE TITLE
Emit `files:node:created` when folder is created

### ISSUE THREAD

**Issue by susnux** [nextcloud-libraries/nextcloud-dialogs#1016]
When creating a new directory in the filepicker we need to emit the eventbus event `files:node:created` to let the files app know (required if the file picker is used on the files app).

For context see https://github.com/nextcloud/server/issues/33323

**Comment by daCaPo** [comment]
I don't know whether this is related to this issue, but with 27.1.1, I experience the following issue:

- With the old file picker, you could create a new folder and then this new folder was immediately opened/selected as copy/move target.
- Now, before you can copy/move files into a new folder, you must
  1. Create a new folder
  2. Select this folder from the list view and
  3. Click the new folder in order to enter it/select it as target for the copy/move operation

_(Furthermore, the dialogue is only in part translated to German, but that needs probably its own ticket)_

**Comment by susnux** [comment]
@daCaPo 
> I don't know whether this is related to this issue, but with 27.1.1, I experience the following issue:

No this is only an issue for Nextcloud 28.

> Furthermore, the dialogue is only in part translated to German, but that needs probably its own ticket

Feel free to help translating Nextcloud at Transifex https://app.transifex.com/nextcloud/
