### ISSUE TITLE
Vue-Rewrite?

### ISSUE THREAD

**Issue by jotoeri** [nextcloud-libraries/nextcloud-dialogs#301]
I recently thought about implementing #300 just like the filePicker. But probably, and in combination with #1 it would be better to first rewrite the own library, before adding new stuff?
Maybe some nice task for the vue-expert @skjnldsv ? 🙈

**Comment by skjnldsv** [comment]
Well, this repo have a bit of everything.
The toast part, should definitely  stay standalone as is, but writing a proper filepicker is definitely needed. There was some work iirc by @eneiluj. So I don't know what the status is so far :)

But having a proper filepicker here, in vue, is definitely needed! :rocket:

**Comment by ChristophWurst** [comment]
Yep, so basically what I wrote into https://github.com/nextcloud/nextcloud-dialogs/issues/1 :D

**Comment by eneiluj** [comment]
@skjnldsv The [file picker Vue component](https://github.com/eneiluj/nextcloud-webdav-filepicker) is released on NPM and used by a few projects AFAIK. I don't know if it fits in Nextcloud in its current state because it embeds all icons and includes some style adjustments. The translations are directly handled with `gettext-parser`.

But the `FileBrowser` sub component could be used in a component that would be designed to work in Nextcloud.
